### ISSUE TITLE
Touches are not passed through to artwork ('.lay') system buttons

### ISSUE THREAD

**Issue by johnparker007** [seleuco/MAME4droid-2024#1]
Thanks for an interesting project @seleuco :) 

The revised OSD doesn't seem to pass the 'button' pressed though in the same way as when using on the desktop build.  These layouts are most commonly used for 'slot machines'.

Steps to reproduce:
1. Load j6indy romset
2. Allow some time for initial set up (you will hear alarm, and machine will reset, then boot)
3. After ~30 seconds, the machine should go into attract mode (so the layout lamps flash to try to draw players in)
4. Tapping on the on-screen '£1' button should insert coins, and then when coins have been inserted, tapping on the flashing 'START' button should spin the reels; on desktop this works, on mame4droid, the touches are not passed through to be processed by the artwork system.

Here is a screenshot of j6indy with those two buttons labelled in magenta:
![image](https://github.com/seleuco/MAME4droid-2024/assets/17624161/5a42d359-8d78-4098-aba9-661208d4fe97)

**Comment by seleuco** [comment]
Wow... That's amazing. I know that artworks are powerful but I didn't test
that. I will take a look when I have some time.

**Comment by johnparker007** [comment]
Awesome, thanks man, it would be cool to play some fruit machines on the go :)  

The 'internal' text-only layouts can also be overridden with external .lay file and .png files in the /artwork folder to provide much richer graphical layouts.  Here's an example of an old one of those from a previous project, they can look pretty good!

https://www.youtube.com/watch?v=V3cYTDEBue8

**Comment by seleuco** [comment]
Sorry. I forgot to answer you. I tried the issue you mentioned and at the time implemented an option in input, mouse, always gaming touch mode that makes the virtual mouse always enabled. In that way I tested the rom that you told me and I was able to interact with the layout. Enjoy fruit machine on the go.

**Comment by johnparker007** [comment]
> Sorry. I forgot to answer you. I tried the issue you mentioned and at the time implemented an option in Mame4droid settings, input, mouse, always gaming touch mode (you have to enable) that makes the virtual mouse always enabled. In that way I tested the rom that you told me and I was able to interact with the layout. Enjoy fruit machines on the go without spend money. 🤣

That's awesome news, thanks for implementing the touchscreen pass through, I will try this out later! :)
