### ISSUE TITLE
How to use autofire function?

### ISSUE THREAD

**Issue by agugu2000** [seleuco/MAME4droid-2024#14]
I switch on autofire plugin,launch a game but without any ingame options about autofire.i remember a "tab" button will bring me a ingame setting in Windows version.
How should i do if i wanna autofire??

**Comment by seleuco** [comment]
**COIN + START at the same time trogle mame UI**

Special

A+START is fast forward (While held, runs game with throttling disabled and with the maximum frameskip).
B+START is toggle UI controls (For emulated systems with keyboard inputs, enable or disable UI control).
R1+START loads a save state
L1+START saves a save state
START+A+B is service mode
SELECT+A+B is soft reset
L1 or A+UP is game PAGE UP
R1 or A+DOWN is game PAGE DOWN<

**Comment by agugu2000** [comment]
Many thanks.
