### ISSUE TITLE
New issue with multilingualism

### ISSUE THREAD

**Issue by agugu2000** [seleuco/MAME4droid-2024#15]
Today we have ver1.71 which contains a shader option.
When this option is activated,ui will use uismall.bdf.
In multilingualism,that means ui only displays English.
I replace uisamll.bdf with a chinese font.In main ui everything goes well,but a mess in in-game ui.

![Screenshot_2024-01-20-22-10-14-160_com seleuco mame4d2024](https://github.com/seleuco/MAME4droid-2024/assets/119565781/ba594aa7-8fa4-4050-863e-efa237410985)

**Comment by seleuco** [comment]
You can set emulation resolution to other bigger resolution instead than auto which is setted automatically when shaders are anabled. That's way your font will be ok..... But scalers shaders needs auto to works better. So is your decision. Your best bet is to try to get/make a new uismall font. 😉

**Comment by agugu2000** [comment]
Do u know the key parameter of uismall font?what's the difference from a normal one?
