### ISSUE TITLE
About disfunction of start button in some game

### ISSUE THREAD

**Issue by agugu2000** [seleuco/MAME4droid-2024#17]
For example:barek3mb.zip
Coins ok,Start no responses

Ver:1.7.2(issues remains)

Hope this is not a request for a individual game supported.Afer all same romset works well in Windows versions of 0.261

**Comment by FlykeSpice** [comment]
You can change the buttons assignments for a system while it is running on Mame:

1) Press Start+Coin button at the same time, it will open a menu.

2) Head to Input Settings->Input Assignments (this system)

3) Select the Input that reads "Start", click on it and press Start button.

4) Done now "Start" input is assigned to the Start button propely.

**Comment by agugu2000** [comment]
> You can change the buttons assignments for a system while it is running on Mame:
> 
> 1. Press Start+Coin button at the same time, it will open a menu.
> 2. Head to Input Settings->Input Assignments (this system)
> 3. Select the Input that reads "Start", click on it and press Start button.
> 4. Done now "Start" input is assigned to the Start button propely.

Yep,i had done the same thing several days ago.
I think the default cfg was set to a wrong keys.
Not a emulation problem.
Close this.
