### ISSUE TITLE
Touch controls

### ISSUE THREAD

**Issue by rabaimor** [seleuco/MAME4droid-2024#19]
The "Touch controller visible" option actually disables/enables the touch controller instead of just hiding/showing it. If this is intended its fine, but adding an option to edit alpha of the touch controls and the exit ; start ;option ; coin (from 100-0) would be awesome. Personally I would set it to 0, and just memorize the locations, so my game recording looks cleaner. Also on the note of touch control aesthetics, an option to use custom designs would be really good for customization. (Then I could set something more modern looking for example.

**Comment by seleuco** [comment]
Ok. I add to the todo list  "adding an option to edit alpha of the touch controls". You are not the first to request it. :)

**Comment by seleuco** [comment]
I'm rolling out a new update 1.8.1 where you can add transparency to the buttons. Enjoy.
