### ISSUE TITLE
Build scripts for mame core.

### ISSUE THREAD

**Issue by FlykeSpice** [seleuco/MAME4droid-2024#23]
Hi seleuco, first off I want to thank you for not giving up on mame4droid even after a decade and doing the huge undertaking of updating to modern mame.

I would like to contribute on improving mame4droid, but there is a big blocker: we don't have the build script to build mame using your osd, and we can't simply edit the build scripts to point to it as there might be additional compiler flags involved and whatnot. (and mame's build system is a chimera itself).

We request something like a patch diff file with your changes for us to apply on upstream mame repository and build from there.

**Comment by seleuco** [comment]
This has already commented here:

https://github.com/seleuco/MAME4droid-2024/issues/8

There's no custom build scripts. Mame itself has an android build system.
