### ISSUE TITLE
Inquiry-Request - HBMAME if possible

### ISSUE THREAD

**Issue by Smoker1** [seleuco/MAME4droid-2024#26]
So for Android, the only Builds you see for Android are MAME2010 (0.139), MAME (Current Builds), or earlier for RetroArch, or your Works, which are awesome.

There is another MAME App for Android that claims to be 0.152, but it only runs the 0.139 Set.

But I am curious to know if you have plans for, or have tried to see about doing HBMAME. To me that would be a nice addition. Just would need to make sure to be able to allow 2 or more Directories, that way have the Normal Sets (1 Directory), then the HBMAME Sets (would be 2 Directories).

**Comment by seleuco** [comment]
hello. I find HBMAME project very interesting.

At the moment I am focused on updating this version that I want to be as pure as possible so that I can update it easily when new versions are released upstream.
