### ISSUE TITLE
Selecting favourites

### ISSUE THREAD

**Issue by romadu** [seleuco/MAME4droid-2024#28]
Is it possible to select favourites for individual roms? There doesn't appear to be a button to do that. Tapping on the star icon generates a pop-up message about adding to favourite with a mouse icon, but I haven't been able to select it.

**Comment by StLouisCPhT** [comment]
I believe you have to set the Mame filters to only show games you have marked as favorites

**Comment by romadu** [comment]
I’m asking how to mark favourites, prior to using the filters.

**Comment by romadu** [comment]
I am able to tap the favourite star. It was a ui screen resolution issue that prevented me previously.
