### ISSUE TITLE
Bluetooth controller right stick not registering

### ISSUE THREAD

**Issue by GerardEarley** [seleuco/MAME4droid-2024#29]
I've a newly purchased bluetooth controller (https://amzn.to/48J4VM6) which works perfectly in a variety of Android games but this controllers right stick is not recognised by mame4droid when I try to bind it's movements in the defines keys screen:
Settings > Input > Game Controller > Define Keys > Player 1

Various bluetooth controller apps report the right stick is working perfectly so it looks like mame4droid is simply not registering this stick.

Games such as Black WIdow and Space Dungeon require the use of the right stick to be played.

Any attention you could pay to this would be appreciated.

🙏

**Comment by seleuco** [comment]
sorry for the delay...

Currently right stick  and analog input is only working with auto detected controllers like xbox one controller but i will support generic ones in next update.

**Comment by GerardEarley** [comment]
Thats wonderful to hear and thank you for such a good playing experience with mame4droid.

**Comment by GerardEarley** [comment]
Both joysticks now work perfectly without and configuration needed and all the twin joystick games I play work flawlessly. 
😋🤙
🙏
