### ISSUE TITLE
Not showing bios archive/files in menu with games. 

### ISSUE THREAD

**Issue by tommylipb00t** [seleuco/MAME4droid-2024#3]
So I've got more than 1k of bios files and some of them (not many, around 30) are showing along with game roms. Is that possible to maybe exclude some files from showing up? or another directory for bios files?
BTW, you did a great job, thank you a lot for that emulator!

**Comment by seleuco** [comment]
That's easy with a custom filter. Launch mame4droid. Navigate to General settings (with coin button), then select System filter -> Custom filter -> Set up filters and add as first filter "available" and a second filter "Not bios". Finally press "Save settings" in previous menu.

**Comment by tommylipb00t** [comment]
ohhh thanks, didnt know that.
Thanks for such a fast feedback!

**Comment by seleuco** [comment]
Happy new year! :)
