### ISSUE TITLE
Disable right stick option

### ISSUE THREAD

**Issue by Stillmars654** [seleuco/MAME4droid-2024#32]
Is the previous version of Mame4Droid 0.139, the ROM asteroids.zip worked with the options under "external controller", "disable right stick" enabled, to allow rotational movement during emulation. That option is not available for this vector based game with the Mame4Droid 2024 app. Thus, making this game unplayable. Would there be a game settings under the mameui to get this same settings?

**Comment by seleuco** [comment]
You should bind rotational buttons on mame ui pressing coin + start at the same time when the game is running on input settings. 
Some older games not map their buttons by default.

**Comment by Stillmars654** [comment]
This worked. Thank you!
