### ISSUE TITLE
Problem when try to install to Android Tv 

### ISSUE THREAD

**Issue by Operater64** [seleuco/MAME4droid-2024#33]
I try to install the apk but i am getting an error..
I have all ready install many apps ...Mame4droid etc.
From Log :
adblink2 5.7
C:/adblink2
05/11/24 13:37:30
C:/Users/Theodor
IP:172.24.0.1
Windows
------------
starting server
Starting connection process
Attempting to connect ...
Connecting.
Process output
"C:/adblink2/adbfiles/adb" connect 192.168.1.12:5555
connected to 192.168.1.12:5555

Connected to 192.168.1.12:5555
Android version: 11
process time duration: 1 seconds
Starting connection process
Attempting to connect ...
Connecting.
Process output
"C:/adblink2/adbfiles/adb" connect 192.168.1.12:5555
already connected to 192.168.1.12:5555

Connected to 192.168.1.12:5555
Android version: 11
process time duration: 1 seconds
Installing C:/Downloads/MAME4droid.2024-1.12.2-release.apk
adb: failed to install C:/Downloads/MAME4droid.2024-1.12.2-release.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

Performing Streamed Install

process time duration: 38 seconds
detaching console process
192.168.1.12:5555
adblink2
Installing C:/Downloads/MAME4droid.2024-1.12.2-release.apk
adb: failed to install C:/Downloads/MAME4droid.2024-1.12.2-release.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

Performing Streamed Install

process time duration: 30 seconds

**Comment by shmox75** [comment]
Same here, My android box can't even pass the package analyser step.

**Comment by seleuco** [comment]
Yes. It's needs android 10 and ARM 64. Most of android boxes are not but shield TV.

**Comment by shmox75** [comment]
> Yes. It's needs android 10 and ARM 64. Most of android boxes are not but shield TV.

Yes unfortunately .. It took me time to figure it out.
PS: I wonder why there is not armv7 version though ?

**Comment by seleuco** [comment]
It's too big. With the 64-bit version it occupies almost the MAXIMUM size to distribute an aab on Google Play since it includes mess, not like retorarch that they had to cut it. Furthermore, the 32-bit code is no longer officially supported by the mame team, much less ARM. Also, this version is designed for modern devices because it is more demanding...

too many problems with the 0.139 already existing...
