### ISSUE TITLE
Sega Model 2 And Graphics Engine

### ISSUE THREAD

**Issue by TheBoxGame** [seleuco/MAME4droid-2024#60]
Will it be possible to play Daytona USA Sega Rally and other games from Sega Model 2 in the new version because Daytona USA has problems with graphics and sound even with FrameSkip 10 and Sega Rally is not worth talking about will it receive OpenGL and Vulkan graphics engine for better game fluidity because in the PC version there are these 2 options OpenGL and Vulkan

**Comment by FlykeSpice** [comment]
It's up to the mame developers decide to optimize Sega Model 2 emulation in the future (which they don't seem interested rn), this is just a frontend.

Besides, adding opengl or vulkan to mame4droid won't do much because the mame core itself only uses software rendering for all its systems.

**Comment by seleuco** [comment]
@FlykeSpice You right. But is not only a front end :). This is a port and yes, mame uses sw rendering as you said and I don’t optimize drivers also. I’m only fixed system 22 so it can work on Android (not work correctly in other Android emulator) but this was an exception and it was very time consuming
