### ISSUE TITLE
Mame's file manager manager keeps pointing to App internal directory when attempting to choose software for a system

### ISSUE THREAD

**Issue by FlykeSpice** [seleuco/MAME4droid-2024#66]
I am unable to choose arbitrary software for a system except when it's available in the software list, making it impossible to load up homebrew roms for a console.

In the mame front-end Configure Folders setting, software media is pointing to my external folder rompath. But it's always opting for the internal path...

**Comment by seleuco** [comment]
You should make a folder called “software” inside the roms folder created in the external storage. Then, with the MAME file manager, you should choose the arbitrary software.  If you has not created the folder previously maybe MAME file manager has been fooled so you should do a clean install or delete internal mame ini files if you have access to internal storage.

**Comment by FlykeSpice** [comment]
Hey, sorry for the late response but it seems that resetting to the default mame settings indeed has fixed it, dumb me.

**Comment by seleuco** [comment]
Great 😀
